/**
 * Tests for Elixir call resolution in the Tier-1 (generic tree-sitter) graph. Builds a
 * small Mix project in a temp dir and asserts that remote calls resolve through the
 * module's `alias` table to the right owner (not to any same-named function elsewhere),
 * that module-level fallbacks and bare-call rules behave, and that defs carry their
 * module and arity.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, rmSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { buildGraph } from "../src/graph/build.js";
import { readGraph, wiringPath } from "../src/graph/write.js";
import type { GraphV1 } from "../src/graph/types.js";

const NAVIGATOR = `defmodule Shop.Checkout.Cart do
  def total(order, opts \\\\ []) do
    line(:a, order, opts)
  end

  def line(:a, _order, _opts), do: :a
  def line(:b, _order, _opts), do: :b

  def helper, do: :h
end
`;

// A second, unrelated \`total/2\` — the bare-name resolver used to see this as an ambiguity
// and drop every cross-file \`total\` call in the repo.
const MAILER = `defmodule Shop.Jobs.Mailer do
  def total(job, args), do: {job, args}
end
`;

const ORDERS = `defmodule Shop.Orders do
  alias Shop.Checkout.Cart
  alias Shop.Payments.{Receipt, Gateway}
  alias Shop.Accounts, as: Acc

  def place(order) do
    result = Cart.total(order, [])
    Gateway.charge()
    Receipt.print(1)
    Acc.owner()
    __MODULE__.local_thing()
    fun = &Cart.total/2
    order |> Cart.line(:b, [])
    {result, fun}
  end

  def local_thing, do: helper()

  defmodule Inner do
    def x, do: Cart.helper()
  end
end
`;

// \`defmodule\` expands aliases in scope: this is Shop.Payments.Gateway, not Payments.Gateway.
const DIRECTOR = `alias Shop.Payments

defmodule Payments.Gateway do
  def charge, do: :charged
end
`;

const PLAY = `defmodule Shop.Payments.Receipt do
  def print(_n), do: :ok
end
`;

// No \`def\` at all — everything is generated by \`use Ecto.Repo\`.
const REPO = `defmodule Shop.Repo do
  use Ecto.Repo, otp_app: :shop, adapter: Ecto.Adapters.Postgres
end
`;

const ACCOUNTS = `defmodule Shop.Accounts do
  alias Shop.Repo

  def owner, do: Repo.get_by(Shop.Accounts.User, email: "x")
end
`;

// Defines \`helper/0\` — a bare \`helper()\` in another module must NOT resolve here.
const OTHER = `defmodule Shop.Util do
  def helper, do: :other
end
`;

function makeFixture(): string {
  const dir = mkdtempSync(join(tmpdir(), "graft-elixir-"));
  writeFileSync(
    join(dir, "mix.exs"),
    `defmodule Shop.MixProject do\n  use Mix.Project\n  def project, do: [app: :shop]\nend\n`,
  );
  mkdirSync(join(dir, "lib/shop/checkout"), { recursive: true });
  mkdirSync(join(dir, "lib/shop/payments"), { recursive: true });
  mkdirSync(join(dir, "lib/shop/jobs"), { recursive: true });
  writeFileSync(join(dir, "lib/shop/checkout/cart.ex"), NAVIGATOR);
  writeFileSync(join(dir, "lib/shop/jobs/mailer.ex"), MAILER);
  writeFileSync(join(dir, "lib/shop/orders.ex"), ORDERS);
  writeFileSync(join(dir, "lib/shop/payments/gateway.ex"), DIRECTOR);
  writeFileSync(join(dir, "lib/shop/payments/receipt.ex"), PLAY);
  writeFileSync(join(dir, "lib/shop/repo.ex"), REPO);
  writeFileSync(join(dir, "lib/shop/accounts.ex"), ACCOUNTS);
  writeFileSync(join(dir, "lib/shop/util.ex"), OTHER);
  return dir;
}

const calls = (g: GraphV1, source: string) =>
  g.edges
    .filter((e) => e.relation === "calls" && e.source === source)
    .map((e) => e.target)
    .sort();

test("Elixir: remote calls resolve through aliases to the owning module", async () => {
  const dir = makeFixture();
  try {
    await buildGraph(dir);
    const g = readGraph(wiringPath(join(dir, "graft")))!;
    const go = calls(g, "lib/shop/orders.ex#place");

    // `alias Shop.Checkout.Cart` + `Cart.total(...)` → the Cart's total, not the Mailer one.
    assert.ok(go.includes("lib/shop/checkout/cart.ex#total"), `place should call Cart.total, got ${go}`);
    assert.ok(!go.includes("lib/shop/jobs/mailer.ex#total"), "must not resolve to the unrelated total/2");
    // `alias Shop.Payments.{Receipt, Gateway}` group form, and a module defined under an aliased prefix.
    assert.ok(go.includes("lib/shop/payments/receipt.ex#print"), "group alias resolves Receipt.print");
    assert.ok(
      go.includes("lib/shop/payments/gateway.ex#charge"),
      "Gateway.charge resolves to the module defined as `Payments.Gateway` after `alias Shop.Payments`",
    );
    // `as:` rename.
    assert.ok(
      go.includes("lib/shop/accounts.ex#owner"),
      "`alias Shop.Accounts, as: Acc` resolves Acc.owner",
    );
    // `__MODULE__.fun()`.
    assert.ok(go.includes("lib/shop/orders.ex#local_thing"), "__MODULE__.local_thing resolves same-file");
    // Multi-clause target: `Cart.line/3` has two heads in one module — one edge, first clause.
    assert.ok(
      go.includes("lib/shop/checkout/cart.ex#line"),
      "piped Cart.line resolves to the first clause",
    );
    assert.ok(!go.includes("lib/shop/checkout/cart.ex#line~2"), "second clause is not a separate target");

    // Nested module sees the outer module's aliases.
    assert.deepEqual(
      calls(g, "lib/shop/orders.ex#Inner.x").concat(calls(g, "lib/shop/orders.ex#x")),
      ["lib/shop/checkout/cart.ex#helper"],
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("Elixir: bare calls stay local; macro-generated targets fall back to the module", async () => {
  const dir = makeFixture();
  try {
    await buildGraph(dir);
    const g = readGraph(wiringPath(join(dir, "graft")))!;

    // `def local_thing, do: helper()` — no `helper/0` in Shop.Orders. A bare call is never
    // another module's function (Shop.Util.helper exists and is the unique global match).
    assert.deepEqual(
      calls(g, "lib/shop/orders.ex#local_thing"),
      [],
      "bare helper() must not resolve cross-file",
    );

    // `Repo.get_by(...)` — Shop.Repo declares no def; the edge lands on the module node.
    assert.deepEqual(calls(g, "lib/shop/accounts.ex#owner"), ["lib/shop/repo.ex#Shop.Repo"]);
    assert.equal(g.edges.find((e) => e.source === "lib/shop/accounts.ex#owner")?.confidence, "inferred");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("Elixir: defs carry owner + arity, modules carry fqn", async () => {
  const dir = makeFixture();
  try {
    await buildGraph(dir);
    const g = readGraph(wiringPath(join(dir, "graft")))!;
    const byId = new Map(g.nodes.map((n) => [n.id, n]));

    assert.equal(byId.get("lib/shop/checkout/cart.ex#total")?.owner, "Shop.Checkout.Cart");
    assert.equal(
      byId.get("lib/shop/checkout/cart.ex#total")?.arity,
      undefined,
      "a default arg makes arity a range → unset",
    );
    assert.equal(byId.get("lib/shop/checkout/cart.ex#line")?.arity, 3);
    assert.equal(byId.get("lib/shop/checkout/cart.ex#helper")?.arity, 0);
    assert.equal(byId.get("lib/shop/payments/gateway.ex#Payments.Gateway")?.fqn, "Shop.Payments.Gateway");
    assert.equal(byId.get("lib/shop/orders.ex#Inner")?.fqn, "Shop.Orders.Inner");
    assert.equal(byId.get("lib/shop/orders.ex#x")?.owner, "Shop.Orders.Inner");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
